---
- name: Install VSCode
  hosts: all 
  become: yes
  gather_facts: true


  
  tasks:

    - name: Install dependencies
      package:
        name: libxss1
        state: present

    - name: Add Microsoft repository key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Microsoft repositiory
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
        state: present

    - name: Install VSCode
      package:
        name: code
        state: present
        


    




